data:
global array vtblListNode: { getValListNode, getNextListNode, 0, 0, 0 }
global array fieldsListNode: { 2, 3, 0 }
global array vtblStack: { 0, 0, popStack, pushStack, 0 }
global array fieldsStack: { 0, 0, 2 }
global array vtblStacker: { 0, 0, 0, 0, doStacker }
global array fieldsStacker: { 0, 0, 0 }
code:

getValListNode(%this):
	%0 = %this + 8
	%1 = load(%0)
	%2 = getelt(%1, 0)
	if %2 then getValListNode1 else NoSuchField0
NoSuchField0:
	fail NoSuchField
getValListNode1:
	%3 = getelt(%this, %2)
	ret %3
getNextListNode(%this):
	%0 = %this + 8
	%1 = load(%0)
	%2 = getelt(%1, 1)
	if %2 then getNextListNode1 else NoSuchField1
NoSuchField1:
	fail NoSuchField
getNextListNode1:
	%3 = getelt(%this, %2)
	ret %3

popStack(%this):
	%0 = %this + 8
	%1 = load(%0)
	%2 = getelt(%1, 2)
	if %2 then popStack1 else NoSuchField2
NoSuchField2:
	fail NoSuchField
popStack1:
	%3 = getelt(%this, %2)
	%4 = %3 == 0
	if %4 then popStack2 else popStack3
popStack2:
	ret 1
popStack3:
	%7 = %this + 8
	%8 = load(%7)
	%9 = getelt(%8, 2)
	if %9 then popStack4 else NoSuchField3
NoSuchField3:
	fail NoSuchField
popStack4:
	%10 = getelt(%this, %9)
	%11 = %10 & 1
	if %11 then NotAPointer0 else popStack5
NotAPointer0:
	fail NotAPointer
popStack5:
	%12 = load(%10)
	%13 = getelt(%12, 0)
	if %13 then popStack6 else NoSuchMethod0
NoSuchMethod0:
	fail NoSuchMethod
popStack6:
	%14 = call(%13, %10)
	%15 = %10 & 1
	if %15 then NotAPointer1 else popStack7
NotAPointer1:
	fail NotAPointer
popStack7:
	%16 = load(%10)
	%17 = getelt(%16, 1)
	if %17 then popStack8 else NoSuchMethod1
NoSuchMethod1:
	fail NoSuchMethod
popStack8:
	%18 = call(%17, %10)
	%19 = %this + 8
	%20 = load(%19)
	%21 = getelt(%20, 2)
	if %21 then popStack9 else NoSuchField4
NoSuchField4:
	fail NoSuchField
popStack9:
	setelt(%this, %21, %18)
	ret %14
pushStack(%this, %v):
	%tmp0 = alloc(4)
	store(%tmp0, @vtblListNode)
	%0 = %tmp0 + 8
	store(%0, @fieldsListNode)
	%1 = %tmp0 & 1
	if %1 then NotAPointer2 else pushStack1
NotAPointer2:
	fail NotAPointer
pushStack1:
	%2 = %tmp0 + 8
	%3 = load(%2)
	%4 = getelt(%3, 0)
	if %4 then pushStack2 else NoSuchField5
NoSuchField5:
	fail NoSuchField
pushStack2:
	setelt(%tmp0, %4, %v)
	%5 = %this + 8
	%6 = load(%5)
	%7 = getelt(%6, 2)
	if %7 then pushStack3 else NoSuchField6
NoSuchField6:
	fail NoSuchField
pushStack3:
	%8 = getelt(%this, %7)
	%9 = %tmp0 & 1
	if %9 then NotAPointer3 else pushStack4
NotAPointer3:
	fail NotAPointer
pushStack4:
	%10 = %tmp0 + 8
	%11 = load(%10)
	%12 = getelt(%11, 1)
	if %12 then pushStack5 else NoSuchField7
NoSuchField7:
	fail NoSuchField
pushStack5:
	setelt(%tmp0, %12, %8)
	%13 = %this + 8
	%14 = load(%13)
	%15 = getelt(%14, 2)
	if %15 then pushStack6 else NoSuchField8
NoSuchField8:
	fail NoSuchField
pushStack6:
	setelt(%this, %15, %tmp0)
	ret 1

doStacker(%this, %stk):
	jump doStacker1
doStacker1:
	%x1 = phi(doStacker, 41, doStacker4, %x2)
	%1 = %x1 > 0
	if %1 then doStacker2 else doStacker5
doStacker2:
	%2 = %stk & 1
	if %2 then NotAPointer4 else doStacker3
NotAPointer4:
	fail NotAPointer
doStacker3:
	%3 = load(%stk)
	%4 = getelt(%3, 3)
	if %4 then doStacker4 else NoSuchMethod2
NoSuchMethod2:
	fail NoSuchMethod
doStacker4:
	%5 = call(%4, %stk, %x1)
	%7 = %x1 - 1
	%8 = %7 << 1
	%x2 = %8 + 1
	jump doStacker1
doStacker5:
	%9 = %stk & 1
	if %9 then NotAPointer5 else doStacker6
NotAPointer5:
	fail NotAPointer
doStacker6:
	%10 = load(%stk)
	%11 = getelt(%10, 2)
	if %11 then doStacker7 else NoSuchMethod3
NoSuchMethod3:
	fail NoSuchMethod
doStacker7:
	%12 = call(%11, %stk)
	jump doStacker8
doStacker8:
	%v1 = phi(doStacker7, %12, doStacker11, %17)
	%13 = %v1 != 0
	if %13 then doStacker9 else doStacker12
doStacker9:
	print(%v1)
	%14 = %stk & 1
	if %14 then NotAPointer6 else doStacker10
NotAPointer6:
	fail NotAPointer
doStacker10:
	%15 = load(%stk)
	%16 = getelt(%15, 2)
	if %16 then doStacker11 else NoSuchMethod4
NoSuchMethod4:
	fail NoSuchMethod
doStacker11:
	%17 = call(%16, %stk)
	jump doStacker8
doStacker12:
	ret 0

main:
	%stk0 = alloc(3)
	store(%stk0, @vtblStack)
	%0 = %stk0 + 8
	store(%0, @fieldsStack)
	%1 = %stk0 & 1
	if %1 then NotAPointer7 else main1
NotAPointer7:
	fail NotAPointer
main1:
	%2 = %stk0 + 8
	%3 = load(%2)
	%4 = getelt(%3, 2)
	if %4 then main2 else NoSuchField9
NoSuchField9:
	fail NoSuchField
main2:
	setelt(%stk0, %4, 1)
	%stkr0 = alloc(2)
	store(%stkr0, @vtblStacker)
	%7 = %stkr0 + 8
	store(%7, @fieldsStacker)
	%8 = %stkr0 & 1
	if %8 then NotAPointer8 else main3
NotAPointer8:
	fail NotAPointer
main3:
	%9 = load(%stkr0)
	%10 = getelt(%9, 4)
	if %10 then main4 else NoSuchMethod5
NoSuchMethod5:
	fail NoSuchMethod
main4:
	%11 = call(%10, %stkr0, %stk0)
	ret 1