class ArrayUtil [
    fields

    method bubbleSort(arr$int[], len$int) returning int with locals i$int, j$int:
        i = 0
        j = 0
        while(i < len): {
            j = ((len-1)-i)
            while(j > 0): {
                ifonly(*arr[j] < *arr[(j-1)]): {
                    _ = ^this.swap(arr, j, (j-1))
                }
                j = (j - 1)
            }
            i = (i + 1)
        }
        return 0
    
    method swap(arr$int[], a$int, b$int) returning int with locals tmp$int:
        tmp = *arr[a]
        *arr[a] = *arr[b]
        *arr[b] = tmp
        return 0
    
    method printArr(arr$int[], len$int) returning int with locals i$int:
        i = 0
        while(i < len): {
            print(*arr[i])
            i = (i+1)
        }
]

main with arr$int[], s$ArrayUtil, len$int:
len = 10
 arr = @int[10]
 *arr[0] = 7
 *arr[1] = 9
 *arr[2] = 4
 *arr[3] = 6
 *arr[4] = 4
 *arr[5] = 4
 *arr[6] = 3
 *arr[7] = 3
 *arr[8] = 10
 *arr[9] = 8
 s = @ArrayUtil
 _ = ^s.bubbleSort(arr, len)
 _ = ^s.printArr(arr, len)
 return 0