class ListNode [
    fields val:int, next:ListNode
    method getNext() returning ListNode with locals:
        return &this.next
    method getVal() returning int with locals:
        return &this.val
]
class Stack [
    fields list:ListNode
    method push(v:int) returning int with locals tmp:ListNode:
        tmp = @ListNode
	    !tmp.val = v
	    !tmp.next = &this.list
	    !this.list = tmp
	    return 0
    
    method pop() returning int with locals tmp:int:
        if (&this.list == null:ListNode): {
            return 0
        } else {
            tmp = ^&this.list.getVal()
            !this.list = ^&this.list.getNext()
            return tmp
        }
]

main with stk:Stack:
    stk = @Stack
    !stk.list = null:ListNode
    _ = ^stk.push(1)
    _ = ^stk.push(3)
    _ = ^stk.push(5)
    _ = ^stk.push(9)
    print(^stk.pop())
    print(^stk.pop())
    print(^stk.pop())
    print(^stk.pop())
    print(^stk.pop())
