class ListNode [
    fields val, next
    method getNext() with locals:
        return &this.next
    method getVal() with locals:
        return &this.val
]
class Stack [
    fields list
    method push(v) with locals tmp:
        tmp = @ListNode
	    !tmp.val = v
	    !tmp.next = &this.list
	    !this.list = tmp
	    return 0
    
    method pop() with locals tmp:
        if (&this.list == 0): {
            return 0
        } else {
            tmp = ^&this.list.getVal()
            !this.list = ^&this.list.getNext()
            return tmp
        }
]

main with stk, tmp, cnt:
    stk = @Stack
    !stk.list = 0
    cnt = 10
    while (cnt > 0): {
        _ = ^stk.push(cnt)
        cnt = (cnt - 1)
        print(cnt)
    }
    while (cnt < 10): {
        tmp = (cnt - 1)
        print(tmp)
        print(^stk.pop())
        cnt = (cnt + 1)
    }

